run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 90s

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  depguard:
    list-type: blacklist
    packages:
      - golang.org/x/net/context
      - github.com/gogo/protobuf/proto

issues:
  # Don't turn off any checks by default. We can do this explicitly if needed.
  exclude-use-default: false
