run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 90s

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  depguard:
    rules:
      main:
        deny:
          - pkg: "golang.org/x/net/context"
          - pkg: "github.com/gogo/protobuf/proto"

issues:
  # Don't turn off any checks by default. We can do this explicitly if needed.
  exclude-use-default: false
